### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by fetzerch**
Testbuild: http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/

Includes: https://github.com/kodi-game/game.libretro.2048/pull/2

### CODE REVIEW

**Comment by fetzerch** [comment]
@garbear have a look at the changes to script-test branches if you like.

**Comment by garbear** [comment]
I had a closer look at .gitignore and some of the text editor sections should be fixed:

```
# build artifacts
build/
obj-x86_64-linux-gnu/
game.*/addon.xml

# commonly used editors
# vim
*.swp

# Eclipse
*.project
*.cproject
.classpath
.settings/

# Sublime
*.sublime-*

# KDevelop 4
*.kdev4

# gedit
*~

# CLion
.idea
```

**Comment by fetzerch** [comment]
Updated the gitignore as requested.
I've disabled android and arm again. Will work on that during christmas vacation. iOS and freebsd should work fine.

**Comment by fetzerch** [comment]
Updated the cores.

**Pull request merged**
