### PR TITLE
[PR 16039] ios Darwin_embedded build change

### PR DESCRIPTION
**Pull request by fuzzard**
https://github.com/xbmc/xbmc/pull/16039

Merge if/when the above PR is merged into kodi master

note: if/when tvos comes into play, i may need to fiddle with this area (iossdk, platform, ios in output name). Can deal with that later.

### CODE REVIEW

**Comment by phunkyfish** [comment]
@fetzerch not sure why this fails. Could you take a look or maybe kick off another build?

**Comment by garbear** [comment]
Failing test case in `test_process_template`

**Comment by fuzzard** [comment]
Updated the pr. Was a test unit cmakelists file. Hopefully that should fix it.
Had a quick glance through the python code in the tests, but didnt see anything in there specifically tied to platform name.

**Comment by garbear** [comment]
looks good to me. objections @fetzerch or @Rechi ?

**Comment by garbear** [comment]
ping @fetzerch to hit the green button

**Pull request merged**
